### ISSUE TITLE
Spring Boot 3, Sanitizer compatibililty

### ISSUE THREAD

**Issue by david-gibbs-ig** [esanchezros/quickfixj-spring-boot-starter#128]
Please see https://github.com/esanchezros/quickfixj-spring-boot-starter-examples/issues/25

**Comment by esanchezros** [comment]
@david-gibbs-ig I just release 2.17.1, which should fix the issue you described in the examples repo. Please let me know if it works for you.

Thanks

**Comment by david-gibbs-ig** [comment]
Thank you. I can see it working in the examples project, I still have problem with my implementation. Most likely error my side, investigating.

**Comment by david-gibbs-ig** [comment]
> @david-gibbs-ig I just release 2.17.1, which should fix the issue you described in the examples repo. Please let me know if it works for you.
> 
> Thanks

Quickfixj Actuator endpoint is working for me, thank you.

**Comment by david-gibbs-ig** [comment]
Fixed in 2.17.1
